//! The embedded Clippity application payload.
//!
//! `scripts/stage-installer-payload.mjs` in the app workspace copies the
//! built `clippity.exe` into `installer/payload/` alongside a
//! `payload.json` describing it. This crate's `build.rs` then compiles
//! both straight into the installer binary, so the shipped
//! `Clippity Setup.exe` is a single self-contained file: no sibling
//! resources folder, no network access, nothing to keep together.
//!
//! This module is the only reader of that embedded data. It verifies the
//! binary against the recorded hash and writes it to the destination the
//! user chose.

use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;
use sha2::{Digest, Sha256};

use installer_infra::error::{other, InstallerError, InstallerResult};
use installer_infra::retry;

// PAYLOAD: Option<&[u8]> and MANIFEST_JSON: Option<&str>, generated by
// build.rs — `None` when no payload was staged at compile time.
include!(concat!(env!("OUT_DIR"), "/payload_embed.rs"));

/// What the staging script recorded about the bundled binary.
#[derive(Debug, Clone, Deserialize)]
pub struct PayloadManifest {
    /// File name the executable installs under.
    pub exe: String,
    /// Version of the application that was staged.
    pub version: String,
    /// Expected size in bytes.
    pub bytes: u64,
    /// Expected SHA-256, lowercase hex.
    pub sha256: String,
}

/// The application compiled into this installer, ready to write out.
#[derive(Debug, Clone)]
pub struct Payload {
    bytes: &'static [u8],
    manifest: PayloadManifest,
}

impl Payload {
    /// Load the payload embedded at compile time.
    ///
    /// A build made without running the staging script has none. That is
    /// a packaging mistake rather than anything the user did, so the
    /// message says exactly which step was skipped.
    pub fn load() -> InstallerResult<Self> {
        let (bytes, raw) = match (PAYLOAD, MANIFEST_JSON) {
            (Some(bytes), Some(raw)) => (bytes, raw),
            _ => {
                return Err(other(
                    "this installer was built without the application inside it. \
                     Run `pnpm stage:payload` and rebuild (or use `pnpm dist`, \
                     which does both in order).",
                ))
            }
        };

        let manifest: PayloadManifest = serde_json::from_str(raw)
            .map_err(|e| other(format!("the embedded payload manifest is unreadable: {e}")))?;

        tracing::info!(
            version = %manifest.version,
            bytes = manifest.bytes,
            "payload resolved"
        );
        Ok(Self { bytes, manifest })
    }

    /// The file name the executable installs under (`Clippity.exe`).
    pub fn exe_name(&self) -> &str {
        &self.manifest.exe
    }

    /// The bundled application's version.
    pub fn version(&self) -> &str {
        &self.manifest.version
    }

    /// The expected SHA-256 (lowercase hex) of the installed executable —
    /// recorded in the installation manifest so repair can detect
    /// corruption.
    pub fn sha256(&self) -> &str {
        &self.manifest.sha256
    }

    /// The installed executable's size in bytes.
    pub fn bytes(&self) -> u64 {
        self.manifest.bytes
    }

    /// Verify the embedded binary against the manifest's size and hash.
    ///
    /// Backs the wizard's "Verifying" step. Compiled-in bytes cannot rot
    /// the way a file on disk can, but the check still earns its place:
    /// it catches a manifest that was staged against a different binary,
    /// and it fails before anything has been written to the user's disk.
    pub fn verify(&self) -> InstallerResult<()> {
        let actual_bytes = self.bytes.len() as u64;
        if actual_bytes != self.manifest.bytes {
            tracing::error!(
                expected = self.manifest.bytes,
                actual = actual_bytes,
                "payload size mismatch"
            );
            return Err(InstallerError::SignatureInvalid);
        }

        let actual = format!("{:x}", Sha256::digest(self.bytes));
        if !actual.eq_ignore_ascii_case(&self.manifest.sha256) {
            tracing::error!(
                expected = %self.manifest.sha256,
                actual = %actual,
                "payload hash mismatch"
            );
            return Err(InstallerError::SignatureInvalid);
        }

        tracing::info!("payload verified");
        Ok(())
    }

    /// Write the application into `destination`, creating it if needed.
    ///
    /// Returns the full path of the installed executable — the same path
    /// the shortcut and Add/Remove Programs entries point at.
    pub fn install_to(&self, destination: &Path) -> InstallerResult<PathBuf> {
        tracing::debug!(dir = %destination.display(), "install_to: create_dir_all");
        retry::with_retry(|| fs::create_dir_all(destination))?;
        let target = destination.join(&self.manifest.exe);
        tracing::debug!(target = %target.display(), exists = target.exists(), "install_to: prepared target");

        // A running Clippity holds a lock on its own exe, so writing over
        // it fails with "access denied". Renaming the old binary out of
        // the way first is what makes reinstall-over-existing and update
        // work; Windows allows renaming a file that is open. Both the rename
        // and the write are retried: a just-written copy is briefly held by
        // antivirus / the search indexer, so an immediate replace can fail
        // transiently even when Clippity itself is not running.
        if target.exists() {
            let backup = destination.join(format!("{}.old", self.manifest.exe));
            let _ = fs::remove_file(&backup);
            tracing::debug!(from = %target.display(), to = %backup.display(), "install_to: rename existing aside");
            retry::with_retry(|| fs::rename(&target, &backup)).map_err(|e| {
                other(format!(
                    "could not replace the existing {} — close Clippity and try again [{e}]",
                    self.manifest.exe
                ))
            })?;
        }

        tracing::debug!(target = %target.display(), bytes = self.bytes.len(), "install_to: write payload");
        retry::with_retry(|| fs::write(&target, self.bytes))?;
        tracing::info!(dest = %target.display(), "payload installed");
        Ok(target)
    }
}
